language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"

env:
  - DJANGO=django==1.9
  - DJANGO=django==1.10
  - DJANGO=django==1.11
  - DJANGO=https://github.com/django/django/archive/master.tar.gz

install:
    - pip install Django

script:
    - python -Wall manage.py test
