language: python

python:
    - "3.5"
    - "3.6"

env:
  - DJANGO=django==1.11
  - DJANGO=django==2.0
  - DJANGO=https://github.com/django/django/archive/master.tar.gz

install:
    - pip install -r requirements.txt
    - python setup.py -q install

script:
    - python -Wall manage.py test
