language: python

python:
    - "3.5"
    - "3.6"

env:
  - DJANGO=django==1.11
  - DJANGO=django==2.0
  - DJANGO=https://github.com/django/django/archive/master.tar.gz

install:
    - pip install $DJANGO
    - python setup.py test

script:
    - python -Wall manage.py test
